# Generated by Django 5.2.1 on 2025-06-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('cancel_order', 'can cancel order')]},
        ),
    ]
